# Generated by Django 5.0.7 on 2024-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
