# Generated by Django 5.0.7 on 2024-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customusermodel_updated_videomodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(default='images.png', null=True, upload_to='video'),
        ),
    ]
