# Generated by Django 5.0.7 on 2024-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='videotitle',
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='videoDescription',
            field=models.TextField(max_length=10000),
        ),
    ]
