# Generated by Django 5.0.7 on 2024-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_videomodel_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='videourl',
            field=models.ImageField(null=True, upload_to='video'),
        ),
    ]
