# Generated by Django 5.0.7 on 2024-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_videomodel_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(default='https://res.cloudinary.com/dmsj2cz1b/image/upload/v1/video/images_c8im89', null=True, upload_to='video'),
        ),
    ]
