# Generated by Django 5.0.7 on 2024-09-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_answermodel_video_videomodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.answermodel'),
        ),
    ]
