# Generated by Django 5.0.7 on 2024-09-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_videomodel_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='user',
            new_name='Commenteduser',
        ),
    ]
