# Generated by Django 5.0.7 on 2024-09-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_user_answermodel_commenteduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='Commenteduser',
            new_name='user',
        ),
    ]
