# Generated by Django 5.0.7 on 2024-09-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_commenteduser_answermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='videourl',
            new_name='videoUrl',
        ),
    ]
