# Generated by Django 5.0.7 on 2024-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_videomodel_answer_answermodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='videoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='video'),
        ),
    ]
