# Generated by Django 5.0.7 on 2025-02-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_videomodel_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
