# Generated by Django 5.0.7 on 2025-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_customusermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(default='https://images.unsplash.com/photo-1497316730643-415fac54a2af?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dGFraW5nJTIwcGhvdG98ZW58MHx8MHx8fDA%3D', null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='videoUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
