# Generated by Django 5.0.7 on 2025-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_customusermodel_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(default='https://res.cloudinary.com/da25rozpm/image/upload/v1745331876/images_cpca3c.png', null=True, upload_to='video'),
        ),
    ]
