# Generated by Django 5.0.7 on 2025-04-28 13:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='images_rujcgg', max_length=255, verbose_name='image'),
        ),
    ]
