# Generated by Django 5.0.7 on 2025-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=models.URLField(blank=True, default='images_rujcgg', null=True),
        ),
    ]
