# Generated by Django 5.0.7 on 2025-04-29 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
